sources:
  - Overpass.glyphs
axisOrder:
  - wght
  - ital
familyName: Overpass
stat:
  Overpass[slnt,wght].ttf:
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
  - name: Slant
    tag: slnt
    values:
    - name: Upright
      value: 0
      flags: 2
    - name: RightLeaning
      value: -10